### ISSUE TITLE
go-ssdp is racy. Possible panics with NATPortMap enabled

### ISSUE THREAD

**Issue by hsanjuan** [libp2p/go-nat#11]
For tracking purposes: https://github.com/koron/go-ssdp/issues/13

I don't think we can do much here (should be addressed in go-ssdp).

**Comment by iulianpascalau** [comment]
This was fixed in commit https://github.com/koron/go-ssdp/commit/2e1c40ed0b5d1dca945828aeef493cc8d47efdf1
Any plans for a new release?

**Comment by vyzo** [comment]
Care for a patch? We can cut a patch release for this.

**Comment by iulianpascalau** [comment]
Should I open a PR?

**Comment by vyzo** [comment]
Yes, please!

**Comment by iulianpascalau** [comment]
on it

**Comment by iulianpascalau** [comment]
created PR #12

**Comment by vyzo** [comment]
I'll bubble it up in go-libp2p as well.

**Comment by vyzo** [comment]
Cut `go-libp2p@v0.4.2` with the patch.
