### ISSUE TITLE
External port is different from internal port

### ISSUE THREAD

**Issue by master255** [libp2p/go-nat#35]
Why is an external port different from an internal port?
It is very bad for decentralized systems if the external port is constantly changing.
There are many reasons of this:
1. I can't use old DHT entries to access the same IDs because the port is already different.
2. I can't quickly create DHT Bootstrap nodes because my clients have a constantly changing external port. This creates the need to use a single, public DHT instead of creating my own DHT network. 
3. When getting the correct information from the DHT, it is possible to not update it. This will reduce the load on the DHT.
4. I can't give to user the ability to choose the port number in the application. All modern applications give the option to select the port.
5. I checked. If the external port is fixed, it speeds up all connections.

I can create a PR.
https://github.com/libp2p/go-nat/blob/002425958110f89f4ae4f49fca50de2cac0ee0e1/natpmp.go#L115C23-L115C23

**Comment by marten-seemann** [comment]
When using a NAT, there's no assumption that the internal port is equivalent to the external port. In fact, that's impossible as soon as you have two clients that want to use the same port (having multiple clients use the same external IP is the entire point of NAT to begin with!).

How ports are assigned, and if they change, depends on your NAT implementation. There are some NATs (namely those with endpoint-dependent address/port mappings) that are notoriously difficult in p2p settings.

**Comment by master255** [comment]
What? Only Libp2p has a different external port than the internal. All other libraries allow port selection. And as a developer of a program (not a library) that uses Libp2p I specify a specific port, but the wrong port is opened. This is not an adequate behavior of the library.
The probability that there will be two clients with the same port out of 50000 is extremely small and if it happens, Nat will choose a random port.
Besides, all my arguments from the post above are ignored.
![image](https://github.com/libp2p/go-nat/assets/5380115/a7314c44-0e62-4ef4-a46b-8ca17309a381)

**Comment by master255** [comment]
For those developers who don't want random ports and want a normal working application - I made a [fork without random ports](https://github.com/master255/go-nat).
Just change github.com/libp2p/go-nat to github.com/master255/go-nat in the Libp2p library.

**Comment by marten-seemann** [comment]
libp2p uses reuseport, so assuming that UPnP succeeds, your external port will be stable for all outgoing connections. It is not "constantly changing" (whatever this is supposed to mean in the first place).

> The probability that there will be two clients with the same port out of 50000 is extremely small and if it happens

And this is incorrect as well. Many apps define a default port (4001 in the case of IPFS), and it's not at all unlikely that you'll have two IPFS nodes running in the same network. In fact, that's a very common scenario.

Now you could argue that for aesthetic reasons, we should try to allocate the local port first, and only fall back to a random port if it's taken. It might be possible to convince me that this would be a good idea. But this would be a purely aesthetic thing, and wouldn't fix any of the alleged problems.

**Comment by master255** [comment]
> libp2p uses reuseport, so assuming that UPnP succeeds, your external port will be stable for all outgoing connections. It is not "constantly changing" (whatever this is supposed to mean in the first place).

It changes constantly when the application is restarted. 

> And this is incorrect as well. Many apps define a default port (4001 in the case of IPFS), and it's not at all unlikely that you'll have two IPFS nodes running in the same network. In fact, that's a very common scenario.

Yes. Indeed. This is a common scenario at the initial stage of development. When there is no release yet and the programmers didn't even think of making the port randomized. But my application is already fine-tuned and I, as an application developer - want to manage the port number myself. Because the user wants to do it. Either way - it doesn't have any drawbacks.

> Now you could argue that for aesthetic reasons, we should try to allocate the local port first, and only fall back to a random port if it's taken. It might be possible to convince me that this would be a good idea. But this would be a purely aesthetic thing, and wouldn't fix any of the alleged problems.

It's not an aesthetic problem, it's a very big problem. Since it speeds up p2p interaction. Other DHT clients don't know that your port has changed and try to communicate with the old port for the first time. And if the old port doesn't change, the DHT requests will get through, but if not, they won't. And this will delay those requests for a while. And there's a lot of problems. In the first post I listed all the ones I know.

**Comment by marten-seemann** [comment]
> > libp2p uses reuseport, so assuming that UPnP succeeds, your external port will be stable for all outgoing connections. It is not "constantly changing" (whatever this is supposed to mean in the first place).
> 
> It changes constantly when the application is restarted.

Then "constantly changing" is clearly a misnomer. This kind of information would have been super important to include in your initial post, as it completely changes the problem that you're trying to solve. We've asked you this before, please put a little bit more effort in your issues here.

A better solution than committing to the internal port would be to choose a random, but consistent (across restarts), port number. This will give you a higher probability that you won't run into collisions, especially when dealing with multiple devices competing for the same port number.

If you're "constantly" going online and offline, you shouldn't enable DHT public mode though. Only nodes that are expecting to stay available for a decent amount of time should use it. Our DHT implementation can only handle so much churn without degrading its performance.

**Comment by master255** [comment]
> A better solution than committing to the internal port would be to choose a random, but consistent (across restarts), port number. This will give you a higher probability that you won't run into collisions, especially when dealing with multiple devices competing for the same port number.

You don't seem to read what I write. It's doesn't have drawbacks. Only advantages. If the external port does not match another device, the internal port will be used. 
This is a complication of the system, not a simplification.
This is the code I'm talking about: https://github.com/master255/go-nat/blob/2478f535ce3dd6aa56702d5949f31f613ba8f237/upnp.go#L266C18-L266C18

**Comment by marten-seemann** [comment]
I did read what you wrote. I don't feel like this discussion is productive in any way though, so I'm going to disengage from here on.

**Comment by master255** [comment]
It seems like you simply don't want to develop a library. Conservatism is a good thing. But it is necessary to learn how other libraries work. Including competitors. For example, Libtorrent uses the logic I propose.
